pool:
  name: VM
steps:
- script: |
   rem "Set environment varibles"
   set "MINGW_HOME=C:/mingw64/bin"
   set "CMKAE_HOME=C:/cmake-3.26.4-windows-x86_64/bin"
   set "CPPTEST_STD_HOME=C:/cpptest_standard-2022.1.0/cpptest"
   set "Path=%CPPTEST_STD_HOME%;%MINGW_HOME%;%CMKAE_HOME%;%Path%"
   
   set "PROJECT_NAME=cpp-project-template"
   set "BUILD_DIR=build"
   
   rem "Compile project"
   rmdir /s /q "%BUILD_DIR%"
   mkdir "%BUILD_DIR%"
   cd "%BUILD_DIR%"
   cmake -DCPPTEST_COVERAGE=ON -DCPPTEST_HOME="%CPPTEST_STD_HOME%" .. -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
   make && make install
   
   rem "Run unit test"
   cd test
   divider_tests.exe
   
   
   rem "Generate coverage report"
   cd "../cpptest-coverage/%PROJECT_NAME%"
   cpptestcli -config "builtin://Coverage" -settings "../../../conf/localsettings.properties" -input "%PROJECT_NAME%.clog" -report "../../reports/cpptest-std/ut"
  displayName: 'Generate Unit Tests with Coverage Report'

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: '**/build/reports/cpptest-std/ut/coverage.xml'
    failOnFailures: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: 'build/reports/cpptest-std/ut'
    ArtifactName: 'coverage-report'

- task: CmdLine@2
  inputs:
    script: 'rm -rf P*'
    workingDirectory: 'C:\Azure_agent\agent\_work\_tasks'